create table if not exists public.tutor_usage (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  retrieval_mode text,
  status text not null default 'started'
    check (status in ('started','success','error','rate_limited')),
  question_chars integer not null default 0 check (question_chars >= 0),
  sources_count integer not null default 0 check (sources_count >= 0),
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  total_tokens integer check (total_tokens is null or total_tokens >= 0),
  provider_cost_usd numeric(12,6) check (provider_cost_usd is null or provider_cost_usd >= 0),
  model text,
  error_code text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists tutor_usage_user_created_idx
  on public.tutor_usage (user_id, created_at desc);

create index if not exists tutor_usage_created_idx
  on public.tutor_usage (created_at desc);

alter table public.tutor_usage enable row level security;

revoke all on table public.tutor_usage from public, anon, authenticated;
revoke all on sequence public.tutor_usage_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.tutor_usage to service_role;
grant usage, select on sequence public.tutor_usage_id_seq to service_role;

comment on table public.tutor_usage is
'Telemetria mínima do Tutor ADPEL. Não armazena o texto das perguntas; registra apenas metadados de uso, tokens, custo e status para controle de abuso e orçamento.';
