create extension if not exists vector with schema extensions;

create table if not exists public.theological_documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  author text,
  institution text,
  document_type text not null,
  source_class text not null,
  authority_level smallint not null check (authority_level between 0 and 100),
  publication_year integer check (publication_year is null or publication_year between 1000 and 2100),
  source_reference text,
  source_url text,
  local_filename text,
  copyright_status text,
  license_notes text,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.theological_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.theological_documents(id) on delete cascade,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null check (length(btrim(content)) > 0),
  section_title text,
  page_start integer check (page_start is null or page_start > 0),
  page_end integer check (page_end is null or page_end > 0),
  topic text,
  token_count integer check (token_count is null or token_count >= 0),
  content_hash text,
  embedding extensions.vector(384),
  embedding_model text,
  embedded_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (document_id, chunk_index),
  check (page_end is null or page_start is null or page_end >= page_start)
);

alter table public.theological_chunks add column if not exists embedding_model text;
alter table public.theological_chunks add column if not exists embedded_at timestamptz;

create index if not exists theological_documents_authority_idx
  on public.theological_documents (authority_level desc)
  where active = true;

create index if not exists theological_documents_institution_idx
  on public.theological_documents (institution)
  where active = true;

create index if not exists theological_chunks_document_id_idx
  on public.theological_chunks (document_id);

create index if not exists theological_chunks_topic_idx
  on public.theological_chunks (topic)
  where topic is not null;

alter table public.theological_documents enable row level security;
alter table public.theological_chunks enable row level security;

revoke all on table public.theological_documents from public, anon, authenticated;
revoke all on table public.theological_chunks from public, anon, authenticated;
revoke all on sequence public.theological_chunks_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.theological_documents to service_role;
grant select, insert, update, delete on table public.theological_chunks to service_role;
grant usage, select on sequence public.theological_chunks_id_seq to service_role;

create or replace function public.match_theological_chunks(
  query_embedding extensions.vector(384),
  match_count integer default 8,
  min_similarity double precision default 0.45,
  min_authority smallint default 0,
  institution_filter text default null
)
returns table (
  chunk_id bigint,
  document_id uuid,
  title text,
  author text,
  institution text,
  document_type text,
  source_class text,
  authority_level smallint,
  publication_year integer,
  source_reference text,
  section_title text,
  page_start integer,
  page_end integer,
  topic text,
  content text,
  similarity double precision
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    c.id,
    d.id,
    d.title,
    d.author,
    d.institution,
    d.document_type,
    d.source_class,
    d.authority_level,
    d.publication_year,
    d.source_reference,
    c.section_title,
    c.page_start,
    c.page_end,
    c.topic,
    c.content,
    (1 - (c.embedding <=> query_embedding))::double precision
  from public.theological_chunks c
  join public.theological_documents d on d.id = c.document_id
  where d.active = true
    and c.embedding is not null
    and d.authority_level >= min_authority
    and (institution_filter is null or d.institution = institution_filter)
    and (1 - (c.embedding <=> query_embedding)) >= min_similarity
  order by c.embedding <=> query_embedding
  limit greatest(1, least(match_count, 20));
$$;

revoke all on function public.match_theological_chunks(
  extensions.vector(384), integer, double precision, smallint, text
) from public, anon, authenticated;

grant execute on function public.match_theological_chunks(
  extensions.vector(384), integer, double precision, smallint, text
) to service_role;
